---
title: "p8105_hw2_pw2550"
author: Ada Wang
date: "2026-03-15"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# library
library(tidyverse)
```

# Problem 1

Import data

```{r}
pols_month = 
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% # automatically converts to integers
  mutate(month = month.abb[month]) %>% 
  mutate(president = case_when(prez_gop == 1 ~ "gop",
                               prez_dem == 1 ~ "dem",
                               TRUE ~ NA)) %>% 
  dplyr::select(-prez_gop, -prez_dem, -day)

snp = 
  read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) %>% 
  mutate(year = ifelse(year <= 15, year + 2000, year + 1900)) %>% 
  arrange(year, month) %>% 
  mutate(month = month.abb[month]) %>% 
  relocate(year, month)

unemployment =
  read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment_percentage"
  ) %>% 
  mutate(month = str_to_sentence(month))
```

Merge

```{r}
# merge snp to pols
merge = 
  pols_month %>% 
  left_join(snp, by = c("year", "month")) %>% 
  left_join(unemployment, by = c("year", "month"))
```

# Problem 2

```{r}
trash = 
  readxl::read_excel("./data/202509 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:M710") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(round(sports_balls, digits = 0)))

professor =
  readxl::read_excel("./data/202509 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M135") %>%
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) 

gwynns =
  readxl::read_excel("./data/202509 Trash Wheel Collection Data.xlsx", sheet = "Gwynns Falls Trash Wheel", range = "A2:L352") %>%
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) 
```





